name: Docker Image Hardener
description: Scans and rewrites Dockerfiles using Trivy and best practices.

inputs:
  dockerfile:
    description: "Comma-separated list of Dockerfiles"
    required: false
  image:
    description: "Comma-separated list of image names to scan"
    required: false
  scan:
    description: "Run Trivy scan"
    required: false
    default: "false"
  rewrite:
    description: "Rewrite Dockerfile(s)"
    required: false
    default: "false"
  fail-on-critical:
    description: "Fail if CRITICAL vulnerabilities are found"
    required: false
    default: "false"
  severity:
    description: "Severity level to filter (e.g. CRITICAL,HIGH)"
    required: false
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  summary:
    description: "Generate GitHub summary markdown table"
    required: false
    default: "false"
  sbom:
    description: "Generate Software Bill of Materials (SBOM)"
    required: false
    default: "false"
  sarif:
    description: "Generate SARIF report (for GitHub Security tab)"
    required: false
    default: "false"
  scorecard:
    description: "Generate security scorecard A/B/C grade"
    required: false
    default: "false"
  output-dir:
    description: "Custom output directory for scan artifacts"
    required: false
    default: "/app/.artifact_scan"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.dockerfile }}"
    - "${{ inputs.image }}"
    - "${{ inputs.scan }}"
    - "${{ inputs.rewrite }}"
    - "${{ inputs.fail-on-critical }}"
    - "${{ inputs.severity }}"
    - "${{ inputs.summary }}"
    - "${{ inputs.sbom }}"
    - "${{ inputs.sarif }}"
    - "${{ inputs.scorecard }}"
    - "${{ inputs.output-dir }}"
